name: News Sender Kindle

services:

  app:
    image: python:3.10-slim
    volumes:
    - type: bind
      source: app
      target: /app
    command: python3 /app/createhtml.py
    restart: unless-stopped


