name: News Sender Kindle

services:

  app:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - GUARDIAN_API_KEY=${GUARDIAN_API_KEY}
      - ENCRYPTION=${ENCRYPTION}
      - EMAIL_SMTP=${EMAIL_SMTP}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - KINDLE_EMAIL=${KINDLE_EMAIL}
    volumes:
    - type: bind
      source: app
      target: /app
    - type: bind
      source: ${OUTPUT_DIRECTORY}
      target: /output
    #command: python3 /app/createhtml.py
    restart: no


