name: News Sender Kindle

services:

  development:
    build:
      context: .
    networks:
      - network1
    volumes:
      - type: bind
        source: config
        target: /config
      - type: bind
        source: src
        target: /src
      - type: bind
        source: morss.py
        target: /usr/local/lib/python3.8/site-packages/morss/morss.py
    environment:
      EMAIL_SMTP: ${EMAIL_SMTP}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      KINDLE_EMAIL: ${KINDLE_EMAIL}
      UPDATE_PERIOD: ${UPDATE_PERIOD}
      FETCH_PERIOD: ${FETCH_PERIOD}
      ITEM: ${ITEM}
      ENCRYPTION: ${ENCRYPTION}
    restart: always

networks:
  network1:
    name: ${NETWORK}
    external: true

