name: Guardian To Kindle

services:

  app:
    build: .
    ports:
      - ${LOCAL_PORT}:5000
    user: "1000:1000"
    environment:
      - PYTHONUNBUFFERED=1
      - PASSWORD=${PASSWORD}
      - GUARDIAN_API_KEY=${GUARDIAN_API_KEY}
      - ENCRYPTION=${ENCRYPTION}
      - EMAIL_SMTP=${EMAIL_SMTP}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - KINDLE_EMAIL=${KINDLE_EMAIL}
      - SEND_EMAIL=${SEND_EMAIL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    volumes:
    - ./app:/app
    restart: unless-stopped


